import { useRef, useState } from "react";
import { Link } from "react-router";
import {
  ArrowLeft,
  BookOpen,
  CheckCircle2,
  ClipboardCopy,
  Download,
  FileText,
  Heart,
  Printer,
  Rocket,
  Scale,
  ThumbsUp,
} from "lucide-react";
import { cn } from "@/lib/utils";

const LOGO_URL = "/logo.png";
const MIN_CHARS = 10;

const DIMENSIONS = [
  {
    icon: Heart,
    title: "Managing Affect",
    prompt:
      "How do you feel about this feedback, and how will you prevent that emotion from blocking your learning?",
    explanation:
      "Managing affect means recognising your emotional response to feedback and preventing it from blocking your ability to learn.",
    placeholder:
      "e.g. I feel a bit defensive, but I will remind myself that this feedback is about my work, not about me as a person…",
    iconBg: "bg-rose-50",
    iconColor: "text-rose-600",
    accentBorder: "border-l-rose-400",
  },
  {
    icon: ThumbsUp,
    title: "Appreciating Feedback",
    prompt: "What is your instructor trying to help you improve?",
    explanation:
      "Appreciating feedback means understanding that comments are a resource to support your learning, not a personal criticism.",
    placeholder:
      "e.g. My instructor wants me to develop a clearer argument structure and engage more critically with sources…",
    iconBg: "bg-amber-50",
    iconColor: "text-amber-600",
    accentBorder: "border-l-amber-400",
  },
  {
    icon: Scale,
    title: "Making Judgements",
    prompt:
      "Which feedback point is most important for improving the quality of your work, and why?",
    explanation:
      "Making judgements means evaluating which feedback comments will have the greatest impact on your work.",
    placeholder:
      "e.g. The most important point is clarifying my thesis statement — without a clear argument the rest of the essay is weakened…",
    iconBg: "bg-sky-50",
    iconColor: "text-sky-600",
    accentBorder: "border-l-sky-400",
  },
  {
    icon: Rocket,
    title: "Taking Action",
    prompt: "What specific action will you take, and by when?",
    explanation:
      "Taking action means converting your priority feedback into a concrete, time-bound improvement plan.",
    placeholder:
      "e.g. I will revise the introduction and clarify the thesis by Thursday, then share with a peer for feedback…",
    iconBg: "bg-teal-soft",
    iconColor: "text-teal",
    accentBorder: "border-l-teal",
  },
] as const;

export default function Worksheet() {
  const [setup, setSetup] = useState({ title: "", instructions: "", feedback: "" });
  const [responses, setResponses] = useState(["", "", "", ""]);
  const [submitted, setSubmitted] = useState(false);
  const [copied, setCopied] = useState(false);
  const outputRef = useRef<HTMLDivElement>(null);

  const filled = responses.filter((r) => r.trim().length >= MIN_CHARS).length;
  const canSubmit = filled === DIMENSIONS.length && setup.title.trim().length > 0;

  function update(i: number, value: string) {
    setResponses((prev) => prev.map((r, j) => (j === i ? value : r)));
  }

  function buildPlanText(): string {
    const lines: string[] = [
      "MY FEEDBACK ACTION PLAN",
      "=".repeat(42),
      "",
      `Assignment:       ${setup.title.trim()}`,
    ];
    if (setup.feedback.trim()) {
      lines.push("", "Feedback Focus:", setup.feedback.trim());
    }
    lines.push(
      "",
      "MANAGING AFFECT",
      "-".repeat(20),
      responses[0]?.trim() ?? "",
      "",
      "APPRECIATING FEEDBACK",
      "-".repeat(20),
      responses[1]?.trim() ?? "",
      "",
      "MAKING JUDGEMENTS",
      "-".repeat(20),
      responses[2]?.trim() ?? "",
      "",
      "TAKING ACTION",
      "-".repeat(20),
      responses[3]?.trim() ?? "",
      "",
      "NEXT STEP",
      "-".repeat(20),
      responses[3]?.trim() ?? "",
      "",
      "=".repeat(42),
      `Generated by ActiOn — Feedback to Action — ${new Date().toLocaleDateString()}`,
    );
    return lines.join("\n");
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(buildPlanText());
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  }

  function handleDownload() {
    const blob = new Blob([buildPlanText()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "feedback-action-plan.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  function handlePrint() {
    window.print();
  }

  function handleGenerate() {
    setSubmitted(true);
    setTimeout(
      () => outputRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }),
      100,
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Print styles — only the plan card is visible when printing */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #ws-print-area, #ws-print-area * { visibility: visible; }
          #ws-print-area { position: fixed; inset: 0; padding: 2rem; }
        }
      `}</style>

      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-primary/30 bg-primary shadow-[0_2px_8px_0_rgb(22_58_95/0.35)]">
        <div className="mx-auto max-w-6xl px-5 py-3 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5 group">
            <img src={LOGO_URL} alt="ActiOn logo" className="w-8 h-8 rounded-lg object-contain" />
            <div className="leading-none">
              <span className="text-sm font-bold text-white tracking-tight">ActiOn</span>
              <span className="hidden sm:block text-[10px] text-white/65 mt-0.5">
                Feedback to Action
              </span>
            </div>
          </Link>
          <div className="flex items-center gap-4">
            <Link
              to="/module/1"
              className="hidden sm:inline-flex items-center gap-1.5 text-xs font-semibold text-white/75 hover:text-white transition-colors"
            >
              <BookOpen className="w-3.5 h-3.5" />
              Start Learning
            </Link>
            <Link
              to="/"
              className="inline-flex items-center gap-1.5 text-sm font-semibold text-white hover:text-white/80 transition-colors"
            >
              <ArrowLeft className="w-3.5 h-3.5" /> Home
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-10 md:py-14">
        {/* Page header */}
        <div className="mb-10">
          <p className="text-[11px] font-bold uppercase tracking-widest text-teal mb-2">
            Feedback Literacy · Worksheet
          </p>
          <h1 className="text-3xl md:text-4xl font-extrabold text-primary tracking-tight leading-tight">
            Feedback Literacy Worksheet
          </h1>
          <p className="mt-3 text-base text-muted-foreground max-w-2xl leading-relaxed">
            Use this worksheet to apply the four feedback literacy dimensions to your own assignment
            feedback. Complete each section, then generate your personalised action plan.
          </p>
        </div>

        {/* Step 1 — Assignment Setup */}
        <div className="rounded-xl border border-border bg-white shadow-card mb-6 overflow-hidden">
          <div className="bg-primary px-5 py-4">
            <p className="text-[10px] font-bold uppercase tracking-widest text-white/55 mb-0.5">
              Step 1
            </p>
            <h2 className="text-base font-bold text-white">Assignment Setup</h2>
          </div>
          <div className="p-5 space-y-4">
            <div>
              <label htmlFor="ws-title" className="block text-sm font-semibold text-primary mb-1.5">
                Assignment Title <span className="text-accent">*</span>
              </label>
              <input
                id="ws-title"
                type="text"
                value={setup.title}
                onChange={(e) => setSetup((s) => ({ ...s, title: e.target.value }))}
                placeholder="e.g. Essay: The Ethics of Artificial Intelligence"
                className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/25 focus:border-primary/40 transition placeholder:text-muted-foreground/60"
              />
            </div>
            <div>
              <label
                htmlFor="ws-instructions"
                className="block text-sm font-semibold text-primary mb-1.5"
              >
                Assignment Instructions / Task Description
              </label>
              <textarea
                id="ws-instructions"
                value={setup.instructions}
                onChange={(e) => setSetup((s) => ({ ...s, instructions: e.target.value }))}
                placeholder="Paste or summarise the assignment brief here…"
                rows={3}
                className="w-full rounded-lg border border-border bg-background px-3.5 py-3 text-sm leading-relaxed focus:outline-none focus:ring-2 focus:ring-primary/25 focus:border-primary/40 resize-y transition placeholder:text-muted-foreground/60"
              />
            </div>
            <div>
              <label
                htmlFor="ws-feedback"
                className="block text-sm font-semibold text-primary mb-1.5"
              >
                Feedback Text{" "}
                <span className="text-muted-foreground font-normal">
                  (paste your instructor's feedback)
                </span>
              </label>
              <textarea
                id="ws-feedback"
                value={setup.feedback}
                onChange={(e) => setSetup((s) => ({ ...s, feedback: e.target.value }))}
                placeholder="Paste the feedback comments you received here…"
                rows={4}
                className="w-full rounded-lg border border-border bg-background px-3.5 py-3 text-sm leading-relaxed focus:outline-none focus:ring-2 focus:ring-primary/25 focus:border-primary/40 resize-y transition placeholder:text-muted-foreground/60"
              />
            </div>
          </div>
        </div>

        {/* Step 2 divider */}
        <div className="flex items-center gap-4 mb-5">
          <div className="h-px flex-1 bg-border" />
          <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            Step 2 · Apply the framework
          </span>
          <div className="h-px flex-1 bg-border" />
        </div>

        {/* Framework dimension cards */}
        <div className="space-y-5 mb-8">
          {DIMENSIONS.map((dim, i) => {
            const Icon = dim.icon;
            const value = responses[i] ?? "";
            const isDone = value.trim().length >= MIN_CHARS;
            return (
              <div
                key={dim.title}
                className={cn(
                  "rounded-xl border border-l-4 bg-white shadow-card transition-shadow",
                  dim.accentBorder,
                  isDone ? "border-border/70 shadow-card-md" : "border-border",
                )}
              >
                <div className="px-5 pt-5 pb-4">
                  <div className="flex items-start gap-3 mb-3">
                    <div
                      className={cn(
                        "shrink-0 w-9 h-9 rounded-lg flex items-center justify-center",
                        dim.iconBg,
                        dim.iconColor,
                      )}
                    >
                      <Icon className="w-4 h-4" />
                    </div>
                    <div className="flex-1 min-w-0 pt-0.5">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h2 className="font-bold text-primary text-sm leading-tight">
                          {dim.title}
                        </h2>
                        {isDone && <CheckCircle2 className="w-3.5 h-3.5 text-teal shrink-0" />}
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5 leading-snug">
                        {dim.explanation}
                      </p>
                    </div>
                  </div>
                  <label
                    htmlFor={`ws-dim-${i}`}
                    className="block text-sm font-semibold text-primary leading-snug"
                  >
                    {dim.prompt}
                  </label>
                </div>
                <div className="px-5 pb-5">
                  <textarea
                    id={`ws-dim-${i}`}
                    value={value}
                    onChange={(e) => update(i, e.target.value)}
                    placeholder={dim.placeholder}
                    rows={3}
                    className={cn(
                      "w-full rounded-lg border bg-background px-3.5 py-3 text-sm leading-relaxed",
                      "focus:outline-none focus:ring-2 focus:ring-primary/25 focus:border-primary/40",
                      "resize-y text-foreground placeholder:text-muted-foreground/60 transition",
                      isDone ? "border-teal/30" : "border-border",
                    )}
                  />
                  <p className="mt-1.5 text-[11px] text-muted-foreground">
                    {value.trim().length === 0
                      ? "Start typing your response…"
                      : isDone
                        ? `${value.trim().split(/\s+/).length} words`
                        : "Keep going — a little more detail helps."}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Generate button */}
        {!submitted && (
          <div className="flex items-center justify-between border-t border-border pt-6 mb-4">
            <p className="text-sm text-muted-foreground">
              {canSubmit
                ? "All sections complete — ready to generate your plan."
                : !setup.title.trim()
                  ? "Add an assignment title to continue."
                  : `${DIMENSIONS.length - filled} section${DIMENSIONS.length - filled !== 1 ? "s" : ""} remaining.`}
            </p>
            <button
              onClick={handleGenerate}
              disabled={!canSubmit}
              className="inline-flex items-center gap-2 rounded-lg bg-accent px-6 py-2.5 text-sm font-bold text-white shadow-card hover:bg-accent/90 disabled:opacity-40 disabled:cursor-not-allowed active:scale-[0.98] transition-all"
            >
              <FileText className="w-4 h-4" />
              Generate My Plan →
            </button>
          </div>
        )}

        {/* ── Output section ──────────────────────────────────────────────── */}
        {submitted && (
          <div ref={outputRef} className="mt-2 mb-8">

            {/* Output header */}
            <div className="flex items-center gap-4 mb-6">
              <div className="h-px flex-1 bg-border" />
              <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                Output
              </span>
              <div className="h-px flex-1 bg-border" />
            </div>

            {/* Success banner */}
            <div className="rounded-xl border border-teal/30 bg-teal-soft px-6 py-4 flex items-center gap-3 mb-5">
              <div className="w-8 h-8 rounded-full bg-teal text-white flex items-center justify-center shrink-0">
                <CheckCircle2 className="w-4 h-4" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-bold text-primary text-sm">Plan generated</p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Your Feedback Action Plan is ready. Copy, download, or print it below.
                </p>
              </div>
              <button
                onClick={() => setSubmitted(false)}
                className="text-xs text-muted-foreground hover:text-primary transition-colors shrink-0"
              >
                ← Edit
              </button>
            </div>

            {/* Action buttons */}
            <div className="flex flex-wrap items-center gap-3 mb-2">
              <button
                onClick={handleCopy}
                className="inline-flex items-center gap-2 rounded-lg bg-teal px-5 py-2.5 text-sm font-bold text-white shadow-card hover:bg-teal/90 active:scale-[0.98] transition-all"
              >
                <ClipboardCopy className="w-4 h-4" />
                Copy Plan
              </button>
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-bold text-white shadow-card hover:bg-primary/90 active:scale-[0.98] transition-all"
              >
                <Download className="w-4 h-4" />
                Download Plan
              </button>
              <button
                onClick={handlePrint}
                className="inline-flex items-center gap-2 rounded-lg border border-border bg-white px-5 py-2.5 text-sm font-bold text-primary shadow-card hover:bg-muted/40 active:scale-[0.98] transition-all"
              >
                <Printer className="w-4 h-4" />
                Print Plan
              </button>
            </div>

            {/* Copy success message */}
            <div className={cn(
              "text-xs font-semibold text-teal flex items-center gap-1.5 mb-5 transition-all duration-300",
              copied ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-1 pointer-events-none",
            )}>
              <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
              Plan copied successfully.
            </div>

            {/* Plan preview card */}
            <div
              id="ws-print-area"
              className="rounded-xl border border-border bg-white shadow-card-md overflow-hidden"
            >
              {/* Plan header */}
              <div className="bg-primary px-6 py-5">
                <p className="text-[10px] font-bold uppercase tracking-widest text-white/55 mb-1">
                  Feedback Literacy · Worksheet
                </p>
                <h2 className="text-lg font-extrabold text-white tracking-tight">
                  My Feedback Action Plan
                </h2>
              </div>

              {/* Assignment title */}
              <div className="px-6 py-4 border-b border-border bg-muted/20">
                <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-1">
                  Assignment
                </p>
                <p className="text-sm font-semibold text-primary">{setup.title.trim()}</p>
              </div>

              {/* Feedback Focus */}
              {setup.feedback.trim() && (
                <div className="px-6 py-4 border-b border-border bg-muted/20">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-1">
                    Feedback Focus
                  </p>
                  <p className="text-sm text-foreground leading-relaxed italic">
                    {setup.feedback.trim()}
                  </p>
                </div>
              )}

              {/* Dimension responses */}
              <div className="divide-y divide-border">
                {DIMENSIONS.map((dim, i) => {
                  const Icon = dim.icon;
                  return (
                    <div key={dim.title} className="px-6 py-5">
                      <div className="flex items-center gap-2.5 mb-2">
                        <div
                          className={cn(
                            "shrink-0 w-7 h-7 rounded-md flex items-center justify-center",
                            dim.iconBg,
                            dim.iconColor,
                          )}
                        >
                          <Icon className="w-3.5 h-3.5" />
                        </div>
                        <span className="text-xs font-bold text-primary">{dim.title}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mb-1.5 leading-snug">
                        {dim.prompt}
                      </p>
                      <p className="text-sm text-foreground leading-relaxed">
                        {responses[i]?.trim()}
                      </p>
                    </div>
                  );
                })}
              </div>

              {/* Next Step — highlighted teal callout */}
              <div className="mx-6 my-5 rounded-xl border border-teal/30 bg-teal-soft px-5 py-4">
                <div className="flex items-center gap-2 mb-2">
                  <Rocket className="w-4 h-4 text-teal shrink-0" />
                  <span className="text-xs font-bold text-teal uppercase tracking-wider">
                    Next Step
                  </span>
                </div>
                <p className="text-sm text-foreground leading-relaxed font-medium">
                  {responses[3]?.trim()}
                </p>
              </div>

              {/* Plan footer */}
              <div className="border-t border-border bg-muted/40 px-6 py-4">
                <p className="text-xs text-muted-foreground">
                  ActiOn · Feedback to Action · {new Date().toLocaleDateString()}
                </p>
              </div>
            </div>

            {/* Bottom nav */}
            <div className="mt-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <Link
                to="/"
                className="text-sm text-muted-foreground hover:text-primary transition-colors"
              >
                ← Back to Home
              </Link>
              <Link
                to="/module/1"
                className="inline-flex items-center gap-2 text-sm font-semibold text-accent hover:text-accent/80 transition-colors"
              >
                <BookOpen className="w-4 h-4" />
                Start the Learning Module →
              </Link>
            </div>
          </div>
        )}

        {/* Bottom nav (pre-submit) */}
        {!submitted && (
          <div className="mt-10 pt-6 border-t border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <Link
              to="/"
              className="text-sm text-muted-foreground hover:text-primary transition-colors"
            >
              ← Back to Home
            </Link>
            <Link
              to="/module/1"
              className="inline-flex items-center gap-2 text-sm font-semibold text-accent hover:text-accent/80 transition-colors"
            >
              <BookOpen className="w-4 h-4" />
              New to feedback literacy? Start the Learning Module →
            </Link>
          </div>
        )}
      </main>
    </div>
  );
}
